import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/menu/header";
import SearchResult from "@/components/search/search-result";
import QueryCliProvider from "@/contexts/query-client-provider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Store App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //container does not center itself automatically (mx-auto)
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryCliProvider>
          <main className="flex min-h-screen flex-col items-center justify-between">
            <Header />
            <div className="container flex mx-auto mt-16">
              <SearchResult>{children}</SearchResult>
            </div>
          </main>
        </QueryCliProvider>
      </body>
    </html>
  );
}
