import type { Metadata } from "next";
import Menu from "@/components/Menu";
import "./globals.css";

export const metadata: Metadata = {
  title: "Loja de Produtos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col lg:flex-row h-screen w-full gap-4 p-3">
          <Menu />
          {children}
        </div>
      </body>
    </html>
  );
}
